export const FETCH_CONTACTS = 'CONTACT:FETCH_CONTACTS';
export const NEW_CONTACT = 'CONTACT:NEW_CONTACT';
export const SET_EMERGENCY = 'CONTACT:SET_EMERGENCY_CONTACT';
export const FETCH_API = 'CONTACT:FETCH_API';